export const companies = [
  {
    id: 1,
    name: "KeepTruckin (Motive)",
    website: "https://www.motive.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Motive_Technologies_logo.svg/2560px-Motive_Technologies_logo.svg.png",
    category: "ELD & Fleet Management",
    description:
      "AI-powered fleet management with ELD compliance, GPS tracking, and safety tools.",
    detailed_features: {
      compliance: { ELD: true, IFTA: true, DVIR: true, HOS: true },
      tracking: {
        GPS: true,
        real_time: true,
        geofencing: true,
        breadcrumbs: true,
      },
      safety: {
        dashcam: true,
        AI_collision_detection: true,
        driver_coaching: true,
        speed_alerts: true,
      },
      operations: {
        dispatch: true,
        route_optimization: true,
        fuel_tracking: true,
        maintenance_alerts: true,
      },
    },
    pricing: {
      ELD_only: "$20/month/vehicle",
      Pro_plan: "$35/month/vehicle",
      Enterprise: "Custom",
      hardware_cost: "$150-$300",
    },
    integrations: ["QuickBooks", "Samsara", "Truckstop.com", "McLeod", "DAT"],
    pros: [
      "User-friendly mobile app",
      "Strong compliance tools",
      "AI safety features",
    ],
    cons: ["Higher pricing", "GPS accuracy issues"],
    ideal_for: ["Small to mid-sized fleets", "Safety-focused"],
    customer_support: {
      phone: "24/7",
      email: true,
      live_chat: true,
      training: "Free onboarding",
    },
    mobile_app_rating: { iOS: 4.7, Android: 4.5 },
  },
  {
    id: 2,
    name: "Samsara",
    website: "https://www.samsara.com",
    logo: "https://logos-world.net/wp-content/uploads/2022/03/Samsara-Logo.png",
    category: "Fleet Management & IoT",
    description:
      "Comprehensive IoT platform with real-time tracking, AI dashcams, and equipment monitoring.",
    detailed_features: {
      compliance: { ELD: true, IFTA: true, DVIR: true, HOS: true },
      tracking: {
        GPS: true,
        real_time: true,
        geofencing: true,
        asset_tracking: true,
        temperature_monitoring: true,
      },
      safety: {
        dashcam: true,
        AI_collision_detection: true,
        driver_scoring: true,
        distracted_driving_alerts: true,
      },
      operations: {
        dispatch: true,
        route_optimization: true,
        fuel_efficiency: true,
        equipment_monitoring: true,
      },
    },
    pricing: {
      ELD_only: "$27/month/vehicle",
      Pro_plan: "Custom Quote",
      Enterprise: "Custom",
      hardware_cost: "$200-$500",
    },
    integrations: ["Salesforce", "QuickBooks", "DAT", "McLeod", "Geotab"],
    pros: ["Best-in-class dashcams", "Robust API", "Excellent analytics"],
    cons: ["Expensive for small fleets", "Complex setup"],
    ideal_for: ["Large fleets", "Mixed assets"],
    customer_support: {
      phone: "24/7",
      email: true,
      live_chat: true,
      training: "Paid onboarding",
    },
    mobile_app_rating: { iOS: 4.8, Android: 4.6 },
  },
  {
    id: 3,
    name: "DAT Freight & Analytics",
    website: "https://www.dat.com",
    logo: "https://mma.prnewswire.com/media/1753556/DAT_Freight_and_Analytics_Logo.jpg",
    category: "Load Board",
    description:
      "North America's largest freight marketplace with load matching and rate analysis.",
    detailed_features: {
      compliance: { ELD: false, IFTA: false, DVIR: false, HOS: false },
      tracking: { GPS: false, real_time: false, geofencing: false },
      safety: { dashcam: false },
      operations: {
        dispatch: false,
        load_board: true,
        rate_analysis: true,
        broker_check: true,
      },
    },
    pricing: {
      ELD_only: "N/A",
      Pro_plan: "$39.95 - $129/month",
      Enterprise: "Custom",
      hardware_cost: "N/A",
    },
    integrations: ["Truckstop.com", "McLeod", "TMW", "QuickBooks"],
    pros: [
      "Largest load database",
      "Powerful rate analytics",
      "Trusted by brokers",
    ],
    cons: ["Expensive for owner-ops", "Fake loads sometimes"],
    ideal_for: ["Owner-operators", "Brokers", "3PLs"],
    customer_support: {
      phone: "Business hours",
      email: true,
      live_chat: true,
      training: "Webinars",
    },
    mobile_app_rating: { iOS: 4.6, Android: 4.4 },
  },
  {
    id: 4,
    name: "Omnitracs",
    website: "https://www.omnitracs.com",
    logo: "https://companieslogo.com/img/orig/QCOM-e332217c.png?t=1648141381",
    category: "Fleet Management & ELD",
    description:
      "Enterprise-grade fleet management with ELD, routing, and compliance solutions.",
    detailed_features: {
      compliance: { ELD: true, IFTA: true, DVIR: true, HOS: true },
      tracking: {
        GPS: true,
        real_time: true,
        geofencing: true,
        asset_tracking: true,
      },
      safety: { dashcam: true, driver_scoring: true },
      operations: {
        dispatch: true,
        route_optimization: true,
        fuel_management: true,
      },
    },
    pricing: {
      ELD_only: "$35/month",
      Pro_plan: "$50/month",
      Enterprise: "Custom",
      hardware_cost: "$300-$800",
    },
    integrations: ["SAP", "Oracle", "McLeod", "TMW"],
    pros: ["Enterprise reliability", "Strong compliance", "Advanced analytics"],
    cons: ["Expensive", "Complex implementation", "Outdated UI"],
    ideal_for: ["Large trucking companies", "Enterprise fleets"],
    customer_support: {
      phone: "24/7",
      email: true,
      live_chat: false,
      training: "Comprehensive",
    },
    mobile_app_rating: { iOS: 4.2, Android: 4.0 },
  },
  {
    id: 5,
    name: "Geotab",
    website: "https://www.geotab.com",
    logo: "https://www.geotab.com/images/logo.svg",
    category: "GPS Tracking",
    description:
      "Open-platform telematics with advanced GPS tracking and data analytics.",
    detailed_features: {
      compliance: { ELD: true, IFTA: true, HOS: true },
      tracking: {
        GPS: true,
        real_time: true,
        geofencing: true,
        engine_data: true,
      },
      safety: { dashcam: false, driver_scoring: true, seatbelt_usage: true },
      operations: {
        dispatch: true,
        maintenance_alerts: true,
        custom_reports: true,
      },
    },
    pricing: {
      ELD_only: "$25/month",
      Pro_plan: "$35/month",
      Enterprise: "Custom",
      hardware_cost: "$150-$300",
    },
    integrations: ["Salesforce", "QuickBooks", "Samsara", "Motive"],
    pros: ["Open platform API", "Excellent analytics", "Reliable hardware"],
    cons: ["ELD needs 3rd party", "Complex UI"],
    ideal_for: ["Data-driven companies", "Mixed fleets"],
    customer_support: {
      phone: "Business hours",
      email: true,
      live_chat: true,
      training: "Certification",
    },
    mobile_app_rating: { iOS: 4.5, Android: 4.3 },
  },
  {
    id: 6,
    name: "Truckstop.com",
    website: "https://www.truckstop.com",
    logo: "https://truckstop.com/logo.svg",
    category: "Load Board & TMS",
    description:
      "Comprehensive load board with TMS integration and freight matching tools.",
    detailed_features: {
      compliance: { ELD: false },
      tracking: { GPS: false },
      safety: { dashcam: false },
      operations: {
        load_board: true,
        TMS: true,
        credit_checks: true,
        rate_analysis: true,
      },
    },
    pricing: {
      ELD_only: "N/A",
      Pro_plan: "$99 - $179/month",
      Enterprise: "Custom",
      hardware_cost: "N/A",
    },
    integrations: ["McLeod", "TMW", "QuickBooks", "DAT", "Motive"],
    pros: ["Strong TMS", "Good credit checks", "Reliable loads"],
    cons: ["Outdated UI", "Mobile app needs work"],
    ideal_for: ["Small to mid-sized fleets", "Flatbed carriers"],
    customer_support: {
      phone: "24/7",
      email: true,
      live_chat: true,
      training: "Webinars",
    },
    mobile_app_rating: { iOS: 4.0, Android: 3.8 },
  },
  {
    id: 7,
    name: "EFS (WEX)",
    website: "https://www.efs.wexinc.com",
    logo: "https://www.wexinc.com/logo.png",
    category: "Fuel Cards",
    description:
      "Fuel payment solutions with discounts, expense controls, and fleet cards.",
    detailed_features: {
      compliance: { IFTA: true },
      tracking: { fuel_tracking: true, fraud_protection: true },
      safety: { dashcam: false },
      operations: { spend_controls: true, detailed_reporting: true },
    },
    pricing: {
      ELD_only: "N/A",
      Pro_plan: "Transaction Fees",
      Enterprise: "Custom",
      hardware_cost: "Free Cards",
    },
    integrations: ["QuickBooks", "SAP", "Fleetio", "McLeod"],
    pros: ["Wide acceptance", "Good discounts", "Fraud protection"],
    cons: ["Fees can add up", "Slow support"],
    ideal_for: ["Fleets of all sizes", "Expense control"],
    customer_support: {
      phone: "24/7",
      email: true,
      live_chat: false,
      training: "Online",
    },
    mobile_app_rating: { iOS: 3.9, Android: 3.7 },
  },
  {
    id: 8,
    name: "Fleetio",
    website: "https://www.fleetio.com",
    logo: "https://assets-global.website-files.com/5f15b5052574591290333225/62b48970e7a17730e461b72e_Fleetio_Logo_Full_Color_RGB.svg",
    category: "Maintenance",
    description: "Cloud-based fleet maintenance and asset management software.",
    detailed_features: {
      compliance: { ELD: false, DVIR: true },
      tracking: { asset_tracking: true, depreciation: true },
      safety: { dashcam: false },
      operations: {
        maintenance_scheduling: true,
        work_orders: true,
        vendor_mgmt: true,
      },
    },
    pricing: {
      ELD_only: "N/A",
      Pro_plan: "$4 - $6/month/vehicle",
      Enterprise: "Custom",
      hardware_cost: "N/A",
    },
    integrations: ["Geotab", "Samsara", "Motive", "QuickBooks"],
    pros: ["Affordable", "Easy to use", "Good mobile app"],
    cons: ["No built-in ELD", "Basic reporting"],
    ideal_for: ["Small fleets", "Maintenance focused"],
    customer_support: {
      phone: "Business hours",
      email: true,
      live_chat: true,
      training: "Docs",
    },
    mobile_app_rating: { iOS: 4.7, Android: 4.5 },
  },
  // Qo'shimcha kompaniyalarni shu formatda qo'shish mumkin
];
